import type { Kysely, SqlBool, Transaction as KyselyTransaction } from 'kysely';
import type {
  NotificationType,
  PaymentMethod,
  RecurrenceFrequency,
  ThemePreference,
  TransactionType,
} from '../types';

/**
 * One schema for both databases. Conventions that make the same queries work on
 * PostgreSQL and SQLite:
 *  - ids are app-generated strings (UUIDs; older rows may hold cuids)
 *  - money columns are integer paise
 *  - calendar dates are 'YYYY-MM-DD' text (PostgreSQL DATE is read back as text)
 *  - timestamps are ISO-8601 strings
 *  - booleans are written as 1/0 and read with `!!` (PostgreSQL accepts '1'/'0')
 */

export interface UserTable {
  id: string;
  name: string;
  email: string;
  passwordHash: string;
  currency: string;
  theme: ThemePreference;
  notifyBudgetAlerts: SqlBool;
  notifyGoalMilestones: SqlBool;
  notifyMonthlySummary: SqlBool;
  createdAt: string;
  updatedAt: string;
}

export interface CategoryTable {
  id: string;
  name: string;
  type: TransactionType;
  color: string;
  icon: string;
  isDefault: SqlBool;
  userId: string;
  createdAt: string;
  updatedAt: string;
}

export interface TransactionTable {
  id: string;
  type: TransactionType;
  /** paise */
  amount: number;
  description: string;
  date: string;
  paymentMethod: PaymentMethod;
  notes: string | null;
  categoryId: string;
  userId: string;
  /** Set when the transaction was generated by a recurring rule */
  recurringId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface RecurringTransactionTable {
  id: string;
  userId: string;
  type: TransactionType;
  /** paise */
  amount: number;
  description: string;
  categoryId: string;
  paymentMethod: PaymentMethod;
  notes: string | null;
  frequency: RecurrenceFrequency;
  interval: number;
  startDate: string;
  endDate: string | null;
  /** Date of the next occurrence still to be created; null once the rule has finished */
  nextDate: string | null;
  /** Number of occurrences already materialised (used to compute the next date without drift) */
  occurrenceCount: number;
  isActive: SqlBool;
  createdAt: string;
  updatedAt: string;
}

export interface BudgetTable {
  id: string;
  userId: string;
  month: number;
  year: number;
  /** paise */
  totalAmount: number;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface BudgetCategoryTable {
  id: string;
  budgetId: string;
  categoryId: string;
  /** paise */
  amount: number;
}

export interface FinancialGoalTable {
  id: string;
  userId: string;
  name: string;
  /** paise */
  targetAmount: number;
  /** paise */
  currentAmount: number;
  targetDate: string | null;
  description: string | null;
  color: string;
  createdAt: string;
  updatedAt: string;
}

export interface NotificationTable {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  isRead: SqlBool;
  dedupeKey: string | null;
  createdAt: string;
}

export interface Database {
  User: UserTable;
  Category: CategoryTable;
  Transaction: TransactionTable;
  RecurringTransaction: RecurringTransactionTable;
  Budget: BudgetTable;
  BudgetCategory: BudgetCategoryTable;
  FinancialGoal: FinancialGoalTable;
  Notification: NotificationTable;
}

export type DB = Kysely<Database> | KyselyTransaction<Database>;

type ColumnSet<T> = Record<keyof T, true>;

/**
 * Every column of every table. Typed as exhaustive records, so adding a column to
 * the interfaces above without listing it here fails to compile — and the schema
 * tests compare this list with the real SQLite and PostgreSQL tables.
 */
export const TABLE_COLUMNS: { [K in keyof Database]: ColumnSet<Database[K]> } = {
  User: {
    id: true, name: true, email: true, passwordHash: true, currency: true, theme: true,
    notifyBudgetAlerts: true, notifyGoalMilestones: true, notifyMonthlySummary: true, createdAt: true, updatedAt: true,
  },
  Category: {
    id: true, name: true, type: true, color: true, icon: true, isDefault: true, userId: true, createdAt: true, updatedAt: true,
  },
  Transaction: {
    id: true, type: true, amount: true, description: true, date: true, paymentMethod: true, notes: true,
    categoryId: true, userId: true, recurringId: true, createdAt: true, updatedAt: true,
  },
  RecurringTransaction: {
    id: true, userId: true, type: true, amount: true, description: true, categoryId: true, paymentMethod: true,
    notes: true, frequency: true, interval: true, startDate: true, endDate: true, nextDate: true,
    occurrenceCount: true, isActive: true, createdAt: true, updatedAt: true,
  },
  Budget: {
    id: true, userId: true, month: true, year: true, totalAmount: true, notes: true, createdAt: true, updatedAt: true,
  },
  BudgetCategory: { id: true, budgetId: true, categoryId: true, amount: true },
  FinancialGoal: {
    id: true, userId: true, name: true, targetAmount: true, currentAmount: true, targetDate: true,
    description: true, color: true, createdAt: true, updatedAt: true,
  },
  Notification: {
    id: true, userId: true, type: true, title: true, message: true, isRead: true, dedupeKey: true, createdAt: true,
  },
};

/** Booleans are written as 1/0 so the same value binds in SQLite and PostgreSQL. */
export const dbBool = (value: boolean): 0 | 1 => (value ? 1 : 0);
